### ISSUE TITLE
Do you want a Dockerfile?

### ISSUE THREAD

**Issue by andrewwippler** [WintrCat/freechess#16]
Like many others, I found this repo through the YouTube video. This is a very nice idea to support my hobby of chess. Rather than waste your bandwidth, I was going to add this package into my home kubernetes cluster.

I like FOSS. Would you like any of these features added to this repo?
- Dockerfile and instructions
- Github actions to run your automated tests
- Constructive criticism of your double use of a variable (CAPTCHA + Dev=true)

**Comment by WintrCat** [comment]
Hi mate - I do not plan to use Docker for this one although I will look into GitHub Actions. With the environment variables, the DEV one was initially meant to do more than just disable the ReCAPTCHA but turns out I never needed it to... so I'll likely disable the CAPTCHA by omission of its variable haha

**Comment by stefnotch** [comment]
I think it would be possible to get rid of the backend entirely. That'd make a Docker setup obsolete.
(See #3 )
