### ISSUE TITLE
Optimisations

### ISSUE THREAD

**Issue by stefnotch** [WintrCat/freechess#3]
I found this thanks to the Youtube video, and was wondering how it works.

After testing it out, I noticed that it repeatedly re-creates a Stockfish worker. And also repeatedly re-requests the stockfish wasm file. 
![image](https://github.com/WintrCat/freechess/assets/10220080/23e2868b-a8e7-4fd7-abb9-9eddb8653248)

I think that could easily be optimised to only create the worker once.

The other thing that I'm curious about is: What's the backend for? It doesn't seem to do anything that couldn't be done in the browser?

**Comment by WintrCat** [comment]
Hi Stef - thanks for watching the video! 😄

Yeah, I definitely agree with you on the Stockfish worker situation. At the time I think it was just a bit of a workaround that ended up sticking since after the first request to the WASM file, subsequent requests use a cached version that's stored locally, so at least you're not requesting for masses of data. Still, it could certainly be optimised, although I think for the moment I'm going to take a bit of a rest from this project because I've worked on it for quite some time and would like to do other things. Nonetheless, it is an open source project - you're free to play around with the code 👍 

With your point about the backend I presume you're talking about why the classification stuff is there, because more generally speaking I use it to serve the webpage to the user and to verify ReCAPTCHA response tokens. Originally the algorithm that classified the moves was going to be proprietary, so I decided to have it on the backend where people on the client-side couldn't see the code for it, but eventually I ended up going open source since I thought that would be a little more transparent for this kind of project... I would have to rework a lot though to now put it on the frontend, so I'm just going to leave it for now since it still works fine 😅. There are also Node packages like Chess.js and pgn-parser that I need to use to classify some of the moves, and, well, I don't know how I would get them to the front-end.

**Comment by stefnotch** [comment]
Regarding the backend, I think chess.js and pgn-parser are bog standard Javascript libraries that will happily run in the frontend.
I do recommend using the typical tooling of today, which is usually Vite.

If you're interested in doing so, I'll happily guide you through it. (My Discord is `stefnotch`, should you want to reach out to me privately.)

**Comment by Theohaines** [comment]
I second this, vite is really good for things like this!

**Comment by stefnotch** [comment]
Closing this as not planned is very reasonable. Overhauling the code to run client side would take multiple days of work, which probably outweighs whatever hosting costs the backend incurs.

If anyone would be interested in this, I'm still available anytime.

(@WintrCat By the way, if you ever need some web dev assistance in a neat future project of yours, feel free to ask me.)

**Comment by WintrCat** [comment]
Yeah honestly I don't think I have the time to put all of the backend stuff to the frontend. I think I'd probably use Webpack & Babel if I were to do so since I'm a little more comfortable with that but at the moment I'd like to be able to spend more time on other fun projects than continue making big changes to Game Report. The cost of the hosting is generally very low for me at the moment such that I have a few years of it covered by donations, so I don't see that becoming an issue any time soon. Also got lots of school and other real life things going on at the moment, so time is not by my side haha

**Comment by stefnotch** [comment]
@WintrCat I'd recommend staying away from Webpack and Babel, since they've basically been superseded by other tools. (Vite being a big one.)

As for what the new ones do differently
- Faster. So much faster, I'll let the [esbuild benchmarks](https://esbuild.github.io/) speak for themselves. Vite uses esbuild under the hood.
- And I heard they're easier to set up than Webpack.

**Comment by Theohaines** [comment]
https://github.com/WintrCat/freechess/assets/91698052/ae8a77a2-9699-4042-9bb9-019c5e3a08c4

**Comment by stefnotch** [comment]
@Theohaines Lol yeah, even the big frameworks who usually hate each others guts all started using Vite.

Also huh, why does it say "Why you should use Vite in 589 easy steps"? I thought it was more opinionated than that (e.g. setting up a Vue js project was a single command).
