### ISSUE TITLE
How I get rid of reCAPTCHA or remove it, running locally?

### ISSUE THREAD

**Issue by MrRedShark77** [WintrCat/freechess#39]

**Comment by tissatussa** [comment]
see my #45 which i just posted today !

btw. having some questions and remarks, we have to post them here because the https://github.com/Theohaines/freechessextra pages have "Issues" disabled .. then i guess WintrCat will forward those to his 'extra' friend.

**Comment by WintrCat** [comment]
Questions about features specific to freechessextra should go to that repository, not here. If issues are disabled there (which I wasn't aware about) then you can contact @TheoHaines directly to request that he reopen them; it does not give you clearance to redirect issues here, because they're not my responsibility to support. His fork is not officially connected to the main repository, it's just one that I recommend.

Nonetheless, the repository that @tissatussa linked is a good place to go if you don't want the ReCAPTCHA. @MrRedShark77

**Comment by Theohaines** [comment]
@tissatussa My repo now has an issues page, I have no idea why it was off but I've turned it on now.
